### ISSUE TITLE
encoded cassette payloads?

### ISSUE THREAD

**Issue by jm3** [quidproquo/mr_video#11]
Does Mr. Video correctly handle cassettes whose yml is saved using binary encoding (via VCR + Mechanize)? When I boot the app and click one of the saved episodes in Chrome, I see the raw encoded payload, not renderable HTML.

### Mr. Video
<img width="282" alt="mr-video-encoding" src="https://user-images.githubusercontent.com/12213/34016095-76aca7ae-e0d5-11e7-8bb4-dc152484b735.png">

### Browser view
<img width="459" alt="cassette-encoding" src="https://user-images.githubusercontent.com/12213/34016083-6deb625e-e0d5-11e7-859a-25184d7b8416.png">

### Cassette yaml
```yml
---
http_interactions:
- request:
    method: get
    uri: https://www.coolwebsite.bro/yes/076591
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip,deflate,identity
      Accept:
      - "*/*"
      User-Agent:
      - Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)
      Accept-Charset:
      - ISO-8859-1,utf-8;q=0.7,*;q=0.7
      Accept-Language:
      - en-us,en;q=0.5
      Host:
      - www.cool.com
      Connection:
      - keep-alive
      Keep-Alive:
      - '300'
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/html;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Server:
      - Server
      Date:
      - Sun, 03 Dec 2017 22:35:45 GMT
      Strict-Transport-Security:
      - max-age=47474747; includeSubDomains; preload
      Vary:
      - Accept-Encoding,User-Agent
      P3p:
      - policyref="https://www.wild.com/w3c/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo
        IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM
        CNT STA HEA PRE LOC GOV OTC "
      X-Frame-Options:
      - SAMEORIGIN
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Expires:
      - "-1"
      Content-Encoding:
      - gzip
      Set-Cookie:
      - session-id-time=2082787201l; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
      - session-id=130-4952975-1123748; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
      X-Cache:
      - Miss from cloudfront
      Via:
      - 1.1 67dc96024835.cloudfront.net (CloudFront)
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        00000SUPERLONGBINARYSTRINGHERE00000FFFFF==
    http_version: 
  recorded_at: Sun, 03 Dec 2017 22:35:47 GMT
- request:
    method: get
    uri: https://www.cool.bro/web/Bopn
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip,deflate,identity
      Accept:
      - "*/*"
      User-Agent:
      - Mozilla/5.0 (Linux; Android 5.1.1; Nexus 7 Build/LMY47V) AppleWebKit/537.36
        (KHTML, like Gecko) Chrome/47.0.2526.76 Safari/537.36
      Accept-Charset:
      - ISO-8859-1,utf-8;q=0.7,*;q=0.7
      Accept-Language:
      - en-us,en;q=0.5
      Host:
      - www.cool.com
      Connection:
      - keep-alive
      Keep-Alive:
      - '300'
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Content-Type:
      - text/html;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Server:
      - Server
      Date:
      - Sun, 03 Dec 2017 23:26:29 GMT
      Strict-Transport-Security:
      - max-age=47474747; includeSubDomains; preload
      Vary:
      - Accept-Encoding,User-Agent
      P3p:
      - policyref="https://www.cool.com/w3c/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo
        IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM
        CNT STA HEA PRE LOC GOV OTC "
      X-Frame-Options:
      - SAMEORIGIN
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Expires:
      - "-1"
      Content-Encoding:
      - gzip
      Set-Cookie:
      - session-id-time=2082787201l; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
      - session-id=140-5769689-9376058; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
      X-Cache:
      - Error from cloudfront
      Via:
      - 1.1 ba841e7f2a9ef2fcd.cloudfront.net (CloudFront)
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        00000SUPERLONGBINARYSTRINGHERE00000FFFFF==
    http_version: 
  recorded_at: Sun, 03 Dec 2017 23:26:29 GMT
- request:
    method: get
    uri: https://www.cool.com/dp/open
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip,deflate,identity
      Accept:
      - "*/*"
      User-Agent:
      - Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)
      Accept-Charset:
      - ISO-8859-1,utf-8;q=0.7,*;q=0.7
      Accept-Language:
      - en-us,en;q=0.5
      Host:
      - www.cool.com
      Connection:
      - keep-alive
      Keep-Alive:
      - '300'
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Server
      Content-Type:
      - text/html;charset=UTF-8
      Strict-Transport-Security:
      - max-age=47474747; includeSubDomains; preload
      Vary:
      - Accept-Encoding,User-Agent
      P3p:
      - policyref="https://www.cool.com/w3c/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo
        IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM
        CNT STA HEA PRE LOC GOV OTC "
      X-Frame-Options:
      - SAMEORIGIN
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Expires:
      - "-1"
      Content-Encoding:
      - gzip
      Date:
      - Sun, 03 Dec 2017 23:56:21 GMT
      Transfer-Encoding:
      - chunked
      Connection:
      - Transfer-Encoding
      - keep-alive
      Set-Cookie:
      - session-id-time=2082787201l; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
      - session-id=141-2432141-8277436; Domain=.cool.com; Expires=Tue, 01-Jan-2036
        08:00:01 GMT; Path=/
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        00000SUPERLONGBINARYSTRINGHERE00000FFFFF==
    http_version: 
  recorded_at: Sun, 03 Dec 2017 23:56:22 GMT
```
